development: &development
  encoding: utf8
  adapter: mysql2
  database: control_center_api_development
  username: root
  password: my_password_sql
  host: 127.0.0.1
  port: 3306

test:
  <<: *development
  database: control_center_api_test

staging:
  <<: *development
  database: control_center_api_staging
  username: root

production:
  <<: *development
  database: control_center_api_production
  username: root
